apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhook
  name: webhook
  namespace: kube-public
  selfLink: /api/v1/namespaces/kube-public/services/webhook
spec:
  clusterIP: 10.27.0.11
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: garm
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
